name: Update README

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  activity:
    name: Update README with activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  blog-posts:
    name: Update README with blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://keanucode.ml/feed/feed.xml'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          max_post_count: 3

  wakatime:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.API_KEY }}
          SHOW_TITLE: true
